name: CuboidRegionClear
version: ${pluginVersion}
main: me.dkim19375.cuboidregionclear.CuboidRegionClear
api-version: 1.16
author: dkim19375
description: Clears cuboid regions
depend:
  - PlaceholderAPI

commands:
  cuboidregionclear:
    description: Main command
    aliases:
      - crc
      - regionclear

permissions:
  cuboidregionclear.command:
    description: Main command
  cuboidregionclear.reload:
    description: Reloads the plugin
  cuboidregionclear.check:
    description: Checks for regions
  cuboidregionclear.reset:
    description: Resets a region